### ISSUE TITLE
Use better Authentication hashing algorithm

### ISSUE THREAD

**Issue by IsmailM** [phenopolis/phenopolis#113]
We currently use `pbkdf2:sha1` for producing salted passwords to store in the DB - which is fine but [experts in the field](http://security.stackexchange.com/q/3165/10691) now advise against using this hashing system.

We should move to using a better hashing system from `passlib`. They have loads of different hashing systems 

Read [this](https://pythonhosted.org/passlib/narr/quickstart.html#creating-and-using-a-cryptcontext) to choose between `argon2`/`bcrypt`/ `pbkdf2_sha256` / `pbkdf2_sha512`/`sha256_crypt` / `sha512_crypt`...

After choosing it's very easy to implement: 
```bash
pip install passlib
pip install argon2_cffi
```
In Python 
```python
from passlib.hash import argon2

hash = argon2.hash("toomanysecrets")
hash
#=> '$argon2i$v=19$m=512,t=2,p=2$kdK6VwpB6F0rhfAeg/C+1w$iTZ9MrtovShWpB1FINA5xg'

argon2.verify("toomanysecrets", hash)
#=>True
```

**Comment by Withington** [comment]
Let's use Argon2 because it's also OWASP's recommendation (Aug2016) https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet

**Comment by Withington** [comment]
I assigned myself to this as this is best done before adding "change password" facility. We need to finalise the algo and re-store the passwords before we let a user change their password.

**Comment by Withington** [comment]
See pull request #132 
Thanks for the instructions above @IsmailM, it made it very straightforward.

**Comment by Withington** [comment]
@pontikos has this (Argon2 authentication) gone live now? If so, I'll close the issue.

**Comment by pontikos** [comment]
Yes.
