### ISSUE TITLE
Broken links on the About page

### ISSUE THREAD

**Issue by Withington** [phenopolis/phenopolis#130]
The links in this text are broken, they all link to about#!

"If you use Phenopolis, please cite us as: Citation 
A UK Inherited Retinal Dystrophy Consortium effort, supported by RP Fighting Blindness, the Medical Research Council and Moorfields Eye Hospital."

@IsmailM I took a guess and assigned this to you?

**Comment by IsmailM** [comment]
I believe this is now fixed 👍

**Comment by Withington** [comment]
Yes, thanks.
