### ISSUE TITLE
Don’t show login btn on home page if already logged in

### ISSUE THREAD

**Issue by IsmailM** [phenopolis/phenopolis#134]
Adapt the home page so that login btn is not shown, if the user is already logged in. 

Add User ID (with dropdown) and my patients to the navbar if already logged in

Change the central Demo login btn to Search / Analyse Data

**Comment by Withington** [comment]
A similar point - if logged in, provide a logout button on the home screen (https://uclex.cs.ucl.ac.uk/). So perhaps change that login btn to a logout btn if the user is already logged in.

Currently it is possible to login, then later hit "Phenopolis" btn and from there you can't logout (unless you go through the login process again). 

It would also be good to provide a route from the home page to the search page if the user is already logged in. As above, if a logged in user hits "Phenopolis" btn then they can't get back to the search page unless they go through the login process again.
