### ISSUE TITLE
easy_install.sh typo in create_index

### ISSUE THREAD

**Issue by logust79** [phenopolis/phenopolis#14]
after various `mongoimport`,  it always tries to create index in `variants`, where it should probably create index for `hpo` or `genes` instead

**Comment by pontikos** [comment]
Hi Jing, I'm sorry I don't understand, it does create index for hpo and genes in the script.

**Comment by logust79** [comment]
Hi Niko, I’ve made corrections to them. Initially, when it imports hpo or genes documents, it always tries to create indexes on db.variants (instead of db.hpo or db.genes), which looks erroneous to me.

**Comment by logust79** [comment]
fixed by [#17](https://github.com/pontikos/phenopolis/commit/c8f4181059291bacfb2c7dde1219d7af7d0497b8)
