### ISSUE TITLE
phenogenon_json not responsive for some hpos

### ISSUE THREAD

**Issue by logust79** [phenopolis/phenopolis#57]
such as https://uclex.cs.ucl.ac.uk/phenogenon_json/HP:0000548 and https://uclex.cs.ucl.ac.uk/phenogenon_json/HP:0000510
but works on https://uclex.cs.ucl.ac.uk/phenogenon_json/HP:0000556

**Comment by pontikos** [comment]
mmm strange it works now, did any one change anything?

**Comment by pontikos** [comment]
This one does not work:
https://uclex.cs.ucl.ac.uk/phenogenon_json/HP:0001098

**Comment by pontikos** [comment]
oh snap, now it does

just slow

**Comment by pontikos** [comment]
Fixed by ajaxification just skat_json left.
