### ISSUE TITLE
compute CADD for every variant 

### ISSUE THREAD

**Issue by pontikos** [phenopolis/phenopolis#7]
http://krishna.gs.washington.edu/download/CADD/v1.3/cadd_v1.3_scripts.tgz

**Comment by pontikos** [comment]
Needs download of CADD dataset.  Request has been put in with cluster support.
Will remind them.

**Comment by pontikos** [comment]
Done. We have downloaded the CADD scripts to run CADD locally.

**Comment by logust79** [comment]
Awesome!
