### ISSUE TITLE
bencode dependency

### ISSUE THREAD

**Issue by IsmailM** [phenopolis/phenopolis#91]
Wouldn't it make more sense add [bencode](https://github.com/phenopolis/phenopolis/tree/master/bencode) as a [dependency](https://pypi.python.org/pypi/bencode/1.0) rather than copying the files over?

CC @Withington

**Comment by pontikos** [comment]
We haven't found it on github.  Might have been moved or renamed.

**Comment by IsmailM** [comment]
Can't we just add it to our pip dependencies - I.e.  "pip install bencode"

**Comment by pontikos** [comment]
The problem we had is that there was many packages called bencode.  Lucy
and I had a look, the one you install with pip is not the right one as far
as we could see.  You are welcome to have a look if you want but I thought
this is the easiest solution.

**Comment by IsmailM** [comment]
Found this: https://github.com/fuzeman/bencode.py, which was updated literally a few days ago...

Have raised an issue to get more info on its usage...

**Comment by pontikos** [comment]
That one looks like the right one but the one you are getting from pip is not that one.
