### ISSUE TITLE
pyhgvs installation error

### ISSUE THREAD

**Issue by logust79** [phenopolis/phenopolis#93]
This one persists but hadn't caused trouble until I tried to remove `offline_analysis`. Any ideas?
```
Processing dependencies for varnorm==0.21
Searching for pyhgvs>=0.8
Reading https://pypi.python.org/simple/pyhgvs/
Couldn't find index page for 'pyhgvs' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for pyhgvs>=0.8
error: Could not find suitable distribution for Requirement.parse('pyhgvs>=0.8')
```

**Comment by Withington** [comment]
@logust79 pyhgvs appears in requirements files as 
hgvs==0.5.0a6
Are you running a branch or fork where the requirements files are different from phenopolis master branch?

**Comment by logust79** [comment]
@Withington `hgvs` and `pyhgvs` are different packages. It seems like `pyhgvs` is required by `varnorm`. I did not change any requirements set in the master. If you look at any previous build server test on travis, you can spot this error [https://travis-ci.org/phenopolis/phenopolis/jobs/205801884#L772]. Just that previously it tolerated the error and carried on with the following tests. But now it won't after I removed offline_analysis

**Comment by IsmailM** [comment]
See https://github.com/weiyi-bitw/varnorm/commit/ca288c5c6866b64ec0d2a692d00ed18db83a7958 (Varnorm moved from hgvs to pyhgvs roughly 8 days ago...


By running `git submodule update --init --remote --recursive` in travis, you are updating each submodule to the lastest version...

**Comment by logust79** [comment]
I guess we have to add another git module as dependency [pyhgvs](https://github.com/counsyl/hgvs)

**Comment by Withington** [comment]
Or ask weiyi-bitw (the author of varnorm) to tag a version of varnorm from last month, that uses hgvs, not pyhgvs. That is if we don't need their latest varnorm version.

Either way, it would be best to depend on a tagged version(s) of varnorm (and possibly pyhgvs) so that we can choose when to update it. Does anyone know weiyi-bitw in order to ask them to tag a version, either one from last month or the current version?

**Comment by IsmailM** [comment]
remove the `--remote` in the `git submodule update --init --remote --recursive` i.e. to:

`git submodule update --init --recursive`

Git submodules is all about linking to a specific commit on another repo....

However, when you add the `--remote` option it updates the submodule to the latest commit...

**Comment by logust79** [comment]
works like a charm! Many thanks @Withington @IsmailM
